compile_pdf:
  image: ctornau/latex
  script:
    - apt-get update -y
    - apt-get install -y inkscape make
    - make all
    - mv main.pdf aif.pdf
  only:
    - master
    - run
  artifacts:
    paths:
      - aif.pdf
      - players_guide.pdf
      - art.pdf
